import type { Metadata } from 'next';
import type { PropsWithChildren } from 'react';

import { SimpleHeader } from '@/components/layout';
import { Flex } from '@/components/ui';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout({ children }: PropsWithChildren) {
  return (
    <Flex direction="column" className="h-screen">
      <SimpleHeader />
      {children}
    </Flex>
  );
}
