import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import type { PropsWithChildren } from 'react';

import MotionProvider from '@/providers/motion/MotionProvider';
import { QueryProvider } from '@/providers/query';

import './globals.css';

const notoSansKR = Noto_Sans_KR({
  variable: '--font-notosans',
  weight: ['100', '300', '400', '500', '600', '700', '900'],
  subsets: ['latin'],
  preload: false,
});

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="ko">
      <body className={`${notoSansKR.variable} ${notoSansKR.className}`}>
        <QueryProvider>
          <MotionProvider>{children}</MotionProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
