import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import type { PropsWithChildren } from 'react';

import MotionProvider from '@/providers/motion/motion-provider';
import { QueryProvider } from '@/providers/query';

import './globals.css';

const notoSansKR = Noto_Sans_KR({
  variable: '--font-notosans',
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
});

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="ko" className={notoSansKR.variable}>
      <body>
        <QueryProvider>
          <MotionProvider>{children}</MotionProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
